apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama-serve
  namespace: codegen-poc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama-serve
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ollama-serve
    spec:
      containers:
      - image: ollama/ollama:latest
        imagePullPolicy: Always
        name: container
        ports:
        - containerPort: 11434
          protocol: TCP
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "ollama pull mistral:latest"]
        resources:
          limits:
            nvidia.com/gpu: "1"
          requests:
            nvidia.com/gpu: "1"
            cpu: "2m" # This process uses very little CPU when idle and about 800m when busy
            memory: "5Gi" # The mistral model uses almost 5GB of RAM
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /.ollama
          name: ollama-storage
        env: # add the new env variable here
        - name: OLLAMA_KEEP_ALIVE
          value: "12h"
      restartPolicy: Always
      volumes:
      - name: ollama-storage
        persistentVolumeClaim:
          claimName: ollama-storage
